theme: jekyll-theme-so-simple

locale: en-US
title: "Personal Blog"
description: "Things I write about programming."
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://alpert.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200 # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-115929693-1" # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: "alper_tekinalp" # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
#category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Alper Tekialp
  picture:
  email: alper.tekinalp@gmail.com
  twitter: alper_tekinalp
  links:
    - title: email
      url: mailto:alper.tekinalp@gmail.com
      icon: fa fa-envelope
    - title: Twitter
      url: https://twitter.com/alper_tekinalp
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/alpert
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: email
    url: mailto:alper.tekinalp@gmail.com
    icon: fa fa-envelope
  - title: Twitter
    url: https://twitter.com/alper_tekinalp
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/alpert
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
